# Generated by Django 2.2.17 on 2020-11-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('element_id', models.AutoField(db_index=True, max_length=128, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=5000)),
                ('index', models.IntegerField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        )
    ]
