package rules.smith;

import org.bson.Document

import com.mindsmiths.ruleEngine.model.Agent
import com.mindsmiths.ruleEngine.model.Heartbeat
import com.mindsmiths.ruleEngine.util.Log
import com.mindsmiths.ruleEngine.util.Agents
import com.mindsmiths.sdk.core.db.DataUtils


rule "Smith's Heartbeat"
    when
        Heartbeat() from entry-point "signals"  // a heartbeat happened
    then
        // logging the info in Terminal
        //Log.info("Smith's heartbeat - num agents: " + Agents.getCount());

        //for(Agent agent : DataUtils.filter(new Document(), Agent.class))
        //    System.out.println(agent.getType());
end
