package rules.smith;

import com.mindsmiths.ruleEngine.model.Heartbeat
import com.mindsmiths.ruleEngine.util.Log
import com.mindsmiths.ruleEngine.util.Agents

import com.mindsmiths.dbAdapter.DBAdapterAPI
import com.mindsmiths.dbAdapter.User
import com.mindsmiths.dbAdapter.FetchResult


rule "Smith's Heartbeat"
    when
        Heartbeat() from entry-point "signals"  // a heartbeat happened
    then
        // logging the info in Terminal
        Log.info("Smith's heartbeat - num agents: " + Agents.getCount());
end

rule "test adapter"
    when
        Heartbeat() from entry-point "signals"  // a heartbeat happened
    then
        DBAdapterAPI.fetchUser("11");
        
end

rule "get fetched"
    when
        res: FetchResult(success == true) from entry-point "signals"
    then
        User user = res.getUsers().get(0);
        user.setSurname('Ghendi');
        DBAdapterAPI.updateUser(user);
        Log.info(res.getUsers());
end