global:
  env:
    PULSAR_URL: '{{ env.PULSAR_URL | default("pulsar://localhost:6650", true) }}'

    MONGO_CLIENT_HOST: '{{ env.MONGO_CLIENT_HOST | default("localhost:27017", true) }}'
    MONGO_CLIENT_USERNAME: '{{ env.MONGO_CLIENT_USERNAME | default("", true) }}'

    POSTGRES_CLIENT_HOST: '{{ env.POSTGRES_CLIENT_HOST | default("localhost", true) }}'
    POSTGRES_CLIENT_PORT: '{{ env.POSTGRES_CLIENT_PORT | default("5432", true) }}'
    POSTGRES_CLIENT_USERNAME: '{{ env.POSTGRES_CLIENT_USERNAME | default("postgres", true) }}'

    REDIS_URL: '{{ env.REDIS_URL | default("localhost:6379", true) }}'

  secrets:
    MONGO_CLIENT_PASSWORD: '{{ env.MONGO_CLIENT_PASSWORD }}'
    POSTGRES_CLIENT_PASSWORD: '{{ env.POSTGRES_CLIENT_PASSWORD | default("postgres", true) }}'
