com.mindsmiths.telegramAdapter.TelegramReceivedMessage:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.ProtoAgent

com.mindsmiths.telegramAdapter.TelegramKeyboardAnswered:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.ProtoAgent

com.mindsmiths.telegramAdapter.TelegramMultiChoiceKeyboardAnswered:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.ProtoAgent
