com.mindsmiths.telegramAdapter.TelegramReceivedMessage:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.Homesmart

com.mindsmiths.telegramAdapter.TelegramKeyboardAnswered:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.Homesmart
