# Generated by Django 2.2.17 on 2020-11-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_index=True, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.Flow')),
            ],
        ),
    ]
